
import { Component, signal, inject, computed, ElementRef, ViewChild, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { GeminiService } from './services/gemini.service';
import { SupabaseService, UserProfile } from './services/supabase.service';

type MediaType = 'image' | 'video';
type AppTab = 'studio' | 'plans';
type PlanTier = 'free' | 'basic' | 'pro';
type PaymentMethod = 'card' | 'paypal' | 'revolut';

interface HistoryItem {
  id: number;
  type: MediaType;
  prompt: string;
  url: string;
  timestamp: Date;
  cost: number;
  folderId?: string | number; 
}

interface Folder {
  id: number;
  name: string;
  icon?: string;
}

interface Plan {
  id: PlanTier;
  name: string;
  price: string;
  credits: number;
  features: string[];
  color: string;
  popular?: boolean;
}

interface CreditPack {
  id: string;
  name: string;
  credits: number;
  price: string;
  popular?: boolean;
}

interface CheckoutItem {
  type: 'plan' | 'credits';
  id: string;
  name: string;
  price: string;
  credits: number;
  description: string;
}

interface EditConfig {
  brightness: number;
  contrast: number;
  saturate: number;
  grayscale: number;
  sepia: number;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styles: []
})
export class AppComponent implements OnInit {
  private geminiService = inject(GeminiService);
  private supabaseService = inject(SupabaseService);

  @ViewChild('imagePreview') imagePreviewRef!: ElementRef<HTMLImageElement>;

  // Config State
  isSupabaseConfigured = signal<boolean>(true);
  showSqlModal = signal<boolean>(false);
  
  // Navigation State
  showLandingPage = signal<boolean>(true);

  // Authentication State
  isLoggedIn = signal<boolean>(false);
  isLoginMode = signal<boolean>(true);
  currentUserId = signal<string | null>(null);
  
  // Auth Inputs
  email = signal<string>('');
  password = signal<string>('');
  signupName = signal<string>('');
  
  // User Profile State
  userName = signal<string>(''); 
  credits = signal<number>(0); 
  currentTier = signal<PlanTier>('free');

  // Navigation & Layout (App Internal)
  activeTab = signal<AppTab>('studio');
  isSidebarOpen = signal<boolean>(false);

  // Folders State
  folders = signal<Folder[]>([
    { id: 1, name: 'Favoritos', icon: 'heart' }
  ]);
  currentFolderId = signal<string | number>('all');
  movingItemId = signal<number | null>(null);

  // Checkout State
  showCheckout = signal<boolean>(false);
  checkoutItem = signal<CheckoutItem | null>(null);
  paymentMethod = signal<PaymentMethod>('card');
  isProcessingPayment = signal<boolean>(false);

  // Prompt Assistant State
  showPromptAssistant = signal<boolean>(false);

  // Editor State
  isEditing = signal<boolean>(false);
  editConfig = signal<EditConfig>({
    brightness: 100,
    contrast: 100,
    saturate: 100,
    grayscale: 0,
    sepia: 0
  });

  // Mock Form Data
  cardName = signal('');
  cardNumber = signal('');
  cardExpiry = signal('');
  cardCvc = signal('');

  // App State
  loginError = signal<string | null>(null);
  prompt = signal<string>('');
  mediaType = signal<MediaType>('image');
  isLoading = signal<boolean>(false);
  generatedUrl = signal<string | null>(null);
  error = signal<string | null>(null);
  statusMessage = signal<string>('');
  
  history = signal<HistoryItem[]>([]);

  // SQL para configurar a BD
  readonly dbSetupSql = `
-- LIMPEZA (Opcional, remove triggers antigos que causam erro)
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();

-- 1. Tabela de Perfis
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  name text,
  credits integer default 30,
  tier text default 'free',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Tabela de Pastas
create table if not exists public.folders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Tabela de Histórico
create table if not exists public.history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  folder_id bigint references public.folders(id) on delete set null,
  type text not null,
  prompt text not null,
  url text,
  cost integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. RLS (Segurança)
alter table public.profiles enable row level security;
alter table public.folders enable row level security;
alter table public.history enable row level security;

-- 5. Políticas (Quem pode ver o quê)
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);

create policy "Users can view own folders" on folders for select using (auth.uid() = user_id);
create policy "Users can insert own folders" on folders for insert with check (auth.uid() = user_id);
create policy "Users can delete own folders" on folders for delete using (auth.uid() = user_id);

create policy "Users can view own history" on history for select using (auth.uid() = user_id);
create policy "Users can insert own history" on history for insert with check (auth.uid() = user_id);
create policy "Users can update own history" on history for update using (auth.uid() = user_id);
create policy "Users can delete own history" on history for delete using (auth.uid() = user_id);
  `.trim();

  promptCategories = {
    styles: ['Fotorealista', 'Cinemático', 'Anime', 'Cyberpunk', 'Pintura a Óleo', '3D Render', 'Pixel Art', 'Minimalista', 'Vaporwave'],
    lighting: ['Luz Natural', 'Golden Hour', 'Luz de Estúdio', 'Neon', 'Volumétrica', 'Escuro e Sombrio', 'Cinematográfico'],
    camera: ['Grande Angular', 'Macro', 'Drone', 'Bokeh (Fundo Desfocado)', '4K', '8K', 'GoPro', 'Lente 35mm', 'Lente 85mm'],
    mood: ['Épico', 'Misterioso', 'Alegre', 'Melancólico', 'Assustador', 'Sereno', 'Futurista', 'Nostálgico']
  };

  plans: Plan[] = [
    { id: 'free', name: 'Grátis', price: '0€', credits: 30, features: ['Acesso ao Imagen 3', 'Geração de Vídeo Padrão', 'Velocidade Normal'], color: 'bg-zinc-800' },
    { id: 'basic', name: 'Básico', price: '9.99€', credits: 150, features: ['150 Créditos Mensais', 'Sem marca d\'água', 'Suporte Prioritário'], color: 'bg-indigo-900', popular: true },
    { id: 'pro', name: 'Profissional', price: '24.99€', credits: 500, features: ['500 Créditos Mensais', 'Geração em Alta Definição', 'Acesso Antecipado a Modelos', 'Suporte VIP'], color: 'bg-purple-900' }
  ];

  creditPacks: CreditPack[] = [
    { id: 'pack_small', name: 'Pack Iniciante', credits: 50, price: '4.99€' },
    { id: 'pack_medium', name: 'Pack Criador', credits: 250, price: '19.99€', popular: true },
    { id: 'pack_large', name: 'Pack Estúdio', credits: 1000, price: '69.99€' }
  ];

  costDisplay = computed(() => {
    if (this.mediaType() === 'video') return '10 créditos';
    return '4-8 créditos';
  });

  filterStyle = computed(() => {
    const c = this.editConfig();
    return `brightness(${c.brightness}%) contrast(${c.contrast}%) saturate(${c.saturate}%) grayscale(${c.grayscale}%) sepia(${c.sepia}%)`;
  });

  filteredHistory = computed(() => {
    const fid = this.currentFolderId();
    const all = this.history();
    if (fid === 'all') return all;
    return all.filter(item => item.folderId === fid);
  });

  recentHistory = computed(() => {
    return this.history().slice(0, 10);
  });

  async ngOnInit() {
    // 1. Verificar se as chaves foram configuradas no código
    if (!this.supabaseService.isConfigured) {
      this.isSupabaseConfigured.set(false);
      return;
    }

    // 2. Verificar sessão ativa
    try {
      const user = await this.supabaseService.getCurrentUser();
      if (user) {
        this.currentUserId.set(user.id);
        this.isLoggedIn.set(true);
        this.showLandingPage.set(false); // Skip landing if logged in
        await this.loadUserData(user.id);
      }
    } catch (e) {
      console.warn("Nenhum utilizador logado ou erro de sessão.");
    }
  }

  enterAuth() {
    this.showLandingPage.set(false);
  }

  async loadUserData(userId: string) {
    try {
      // 1. Profile
      const profile = await this.supabaseService.getProfile(userId);
      if (profile) {
        this.userName.set(profile.name);
        this.credits.set(profile.credits);
        this.currentTier.set(profile.tier);
      } else {
        // Fallback se o perfil ainda não existir
        this.userName.set('Utilizador');
        this.credits.set(30);
      }

      // 2. Folders
      const folders = await this.supabaseService.getFolders(userId);
      this.folders.set([
        { id: 1, name: 'Favoritos', icon: 'heart' },
        ...folders.map((f: any) => ({ id: f.id, name: f.name }))
      ]);

      // 3. History
      const history = await this.supabaseService.getHistory(userId);
      this.history.set(history);

    } catch (err: any) {
      console.error('Erro ao carregar dados:', err);
      // Se o erro indicar falta de tabelas, avisar o user
      if (err.message?.includes('relation') || err.code === '42P01') {
        alert('As tabelas do Supabase não existem. Use o botão "Configurar Base de Dados (SQL)" no ecrã de login.');
        await this.onLogout();
      }
    }
  }

  // --- SQL HELPER ---
  toggleSqlModal() {
    this.showSqlModal.update(v => !v);
  }

  copySqlToClipboard() {
    navigator.clipboard.writeText(this.dbSetupSql).then(() => {
      alert('Código SQL copiado! Cole no "SQL Editor" do Supabase e execute.');
    });
  }

  toggleAuthMode() {
    this.isLoginMode.update(v => !v);
    this.loginError.set(null);
  }

  async onAuthAction() {
    const emailVal = this.email().trim();
    const passVal = this.password().trim();
    const nameVal = this.signupName().trim();

    if (!emailVal || !emailVal.includes('@')) {
      this.loginError.set('Email inválido.');
      return;
    }
    if (!passVal || passVal.length < 6) {
      this.loginError.set('A palavra-passe deve ter 6+ caracteres.');
      return;
    }

    this.loginError.set(null);
    this.isLoading.set(true);

    try {
      if (this.isLoginMode()) {
        const { user } = await this.supabaseService.signIn(emailVal, passVal);
        if (user) {
          this.currentUserId.set(user.id);
          this.isLoggedIn.set(true);
          await this.loadUserData(user.id);
        }
      } else {
        if (!nameVal) {
          this.loginError.set('Nome é obrigatório.');
          this.isLoading.set(false);
          return;
        }
        
        const data = await this.supabaseService.signUp(emailVal, passVal, nameVal);
        
        if (data.user && !data.session) {
           alert('Conta criada! Verifique o email para confirmar antes de entrar.');
           this.isLoginMode.set(true); 
        } else if (data.user && data.session) {
          this.currentUserId.set(data.user.id);
          this.isLoggedIn.set(true);
          await this.loadUserData(data.user.id);
          alert('Bem-vindo ao GenAI Studio!');
        }
      }
    } catch (err: any) {
      const errorMsg = err.message || '';
      
      // TRATAMENTO DE ERROS COMUNS
      if (errorMsg.includes('User already registered') || errorMsg.includes('already registered')) {
        this.loginError.set('Este email já está registado. A mudar para Login...');
        this.isLoginMode.set(true); 
      } else if (errorMsg.includes('Database error saving new user')) {
        this.loginError.set('Erro na Base de Dados. Provavelmente faltam as tabelas.');
        this.showSqlModal.set(true); // Abre o modal de ajuda automaticamente
      } else {
        this.loginError.set(errorMsg || 'Erro de autenticação.');
      }
    } finally {
      this.isLoading.set(false);
    }
  }

  async onLogout() {
    await this.supabaseService.signOut();
    this.isLoggedIn.set(false);
    this.currentUserId.set(null);
    this.email.set('');
    this.password.set('');
    this.history.set([]);
    this.folders.set([{ id: 1, name: 'Favoritos', icon: 'heart' }]);
    this.prompt.set('');
    this.generatedUrl.set(null);
    this.showLandingPage.set(true); // Return to landing page
  }

  // --- FOLDER LOGIC ---

  toggleSidebar() {
    this.isSidebarOpen.update(v => !v);
  }

  async createFolder() {
    const name = prompt('Nome da nova pasta:');
    if (name && name.trim() && this.currentUserId()) {
      try {
        const newFolder = await this.supabaseService.createFolder(this.currentUserId()!, name.trim());
        this.folders.update(prev => [...prev, { id: newFolder.id, name: newFolder.name }]);
      } catch (e: any) {
        alert('Erro ao criar pasta: ' + e.message);
      }
    }
  }

  async deleteFolder(id: number, event: Event) {
    event.stopPropagation();
    if (id === 1) return; // Cannot delete favorites
    
    if (confirm('Tem a certeza? Os itens nesta pasta voltarão para "Todas".')) {
      try {
        await this.supabaseService.deleteFolder(id);
        // UI Update
        this.history.update(items => items.map(i => i.folderId === id ? { ...i, folderId: undefined } : i));
        this.folders.update(prev => prev.filter(f => f.id !== id));
        if (this.currentFolderId() === id) {
          this.currentFolderId.set('all');
        }
      } catch (e: any) {
        alert('Erro ao apagar pasta: ' + e.message);
      }
    }
  }

  selectFolder(id: string | number) {
    this.currentFolderId.set(id);
    if (window.innerWidth < 768) {
      this.isSidebarOpen.set(false);
    }
  }

  toggleMoveMenu(itemId: number, event: Event) {
    event.stopPropagation();
    if (this.movingItemId() === itemId) {
      this.movingItemId.set(null);
    } else {
      this.movingItemId.set(itemId);
    }
  }

  async moveItemToFolder(item: HistoryItem, folderId: number | 'all') {
    const finalId = folderId === 'all' ? null : folderId;
    
    try {
      await this.supabaseService.moveItemToFolder(item.id, finalId);
      
      this.history.update(prev => prev.map(i => {
        if (i.id === item.id) {
          return { ...i, folderId: finalId || undefined };
        }
        return i;
      }));
      this.movingItemId.set(null);
    } catch (e) {
      console.error(e);
    }
  }
  
  async deleteItem(item: HistoryItem, event: Event) {
    event.stopPropagation();
    if (confirm('Tem a certeza que deseja eliminar esta criação? Esta ação não pode ser desfeita.')) {
      try {
        await this.supabaseService.deleteHistoryItem(item.id);
        this.history.update(prev => prev.filter(i => i.id !== item.id));
        
        // Se o item apagado for o que está a ser visualizado/editado, limpar
        if (this.generatedUrl() === item.url) {
            this.generatedUrl.set(null);
            this.prompt.set('');
        }
      } catch (e: any) {
        alert('Erro ao eliminar: ' + e.message);
      }
    }
  }

  getFolderName(id: string | number): string {
    if (id === 'all') return 'Todas as Criações';
    const folder = this.folders().find(f => f.id === id);
    return folder ? folder.name : 'Desconhecida';
  }

  // --- EDITOR & GEN LOGIC ---

  toggleEditor() {
    if (this.currentTier() === 'free') {
      const wantUpgrade = confirm('A edição de imagem e vídeo é exclusiva para planos Básico e Profissional. Deseja ver os planos?');
      if (wantUpgrade) {
        this.activeTab.set('plans');
        window.scrollTo({ top: 0, behavior: 'smooth' });
      }
      return;
    }
    this.isEditing.update(v => !v);
    if (this.isEditing()) {
      this.editConfig.set({ brightness: 100, contrast: 100, saturate: 100, grayscale: 0, sepia: 0 });
    }
  }

  updateEditConfig(key: keyof EditConfig, event: Event) {
    const value = Number((event.target as HTMLInputElement).value);
    this.editConfig.update(prev => ({ ...prev, [key]: value }));
  }

  downloadEditedImage() {
    if (this.mediaType() !== 'image') {
      alert('Para vídeos, o download baixará o arquivo original.');
      const link = document.createElement('a');
      link.href = this.generatedUrl()!;
      link.download = 'video-editado.mp4';
      link.click();
      return;
    }
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    const img = this.imagePreviewRef.nativeElement;
    if (!ctx || !img) return;

    canvas.width = img.naturalWidth;
    canvas.height = img.naturalHeight;
    const c = this.editConfig();
    ctx.filter = `brightness(${c.brightness}%) contrast(${c.contrast}%) saturate(${c.saturate}%) grayscale(${c.grayscale}%) sepia(${c.sepia}%)`;
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);

    const link = document.createElement('a');
    link.download = `imagem-editada-${Date.now()}.jpg`;
    link.href = canvas.toDataURL('image/jpeg', 0.9);
    link.click();
  }

  appendTag(tag: string) {
    const current = this.prompt();
    if (current.toLowerCase().includes(tag.toLowerCase())) return;
    let separator = '';
    if (current.length > 0) {
      separator = !current.trim().endsWith(',') ? ', ' : ' ';
    }
    this.prompt.set(current + separator + tag);
  }

  toggleAssistant() {
    this.showPromptAssistant.update(v => !v);
  }

  // --- CHECKOUT ---

  openCheckoutForPlan(plan: Plan) {
    if (plan.id === 'free') {
      alert('Plano Grátis ativado.');
      // Na realidade, faria um downgrade na DB
      return;
    }
    this.checkoutItem.set({
      type: 'plan',
      id: plan.id,
      name: `Plano ${plan.name}`,
      price: plan.price,
      credits: plan.credits,
      description: `Subscrição mensal com ${plan.credits} créditos`
    });
    this.showCheckout.set(true);
  }

  openCheckoutForPack(pack: CreditPack) {
    this.checkoutItem.set({
      type: 'credits',
      id: pack.id,
      name: pack.name,
      price: pack.price,
      credits: pack.credits,
      description: `Compra única de ${pack.credits} créditos extra`
    });
    this.showCheckout.set(true);
  }

  closeCheckout() {
    if (this.isProcessingPayment()) return;
    this.showCheckout.set(false);
    this.checkoutItem.set(null);
  }

  async processPayment() {
    if (this.isProcessingPayment()) return;
    
    if (this.paymentMethod() === 'card') {
      if (!this.cardNumber() || !this.cardName()) {
        alert('Dados do cartão incompletos.');
        return;
      }
    }

    this.isProcessingPayment.set(true);
    await new Promise(resolve => setTimeout(resolve, 2000));

    const item = this.checkoutItem();
    const uid = this.currentUserId();

    if (item && uid) {
      try {
        if (item.type === 'credits') {
          const newCredits = this.credits() + item.credits;
          await this.supabaseService.updateCredits(uid, newCredits);
          this.credits.set(newCredits);
        } else if (item.type === 'plan') {
          // Simplification: Set credits to plan amount and update tier
          await this.supabaseService.updateTier(uid, item.id, item.credits);
          this.currentTier.set(item.id as PlanTier);
          this.credits.set(item.credits);
        }
        alert('Pagamento confirmado!');
      } catch (e: any) {
        alert('Erro ao processar na DB: ' + e.message);
      }
      this.activeTab.set('studio');
    }

    this.isProcessingPayment.set(false);
    this.closeCheckout();
  }

  // --- GENERATION ---

  calculateCost(): number {
    if (this.mediaType() === 'video') return 10;
    return Math.floor(Math.random() * (8 - 4 + 1)) + 4;
  }

  async onGenerate() {
    const currentPrompt = this.prompt().trim();
    if (!currentPrompt) {
      this.error.set('Por favor, digite um prompt.');
      return;
    }

    const cost = this.calculateCost();
    if (this.credits() < cost) {
      this.error.set(`Créditos insuficientes (${cost}).`);
      return;
    }

    this.error.set(null);
    this.generatedUrl.set(null);
    this.isLoading.set(true);
    this.isEditing.set(false);

    try {
      let url: string;
      if (this.mediaType() === 'image') {
        this.statusMessage.set(`A gerar imagem (${cost} créditos)...`);
        url = await this.geminiService.generateImage(currentPrompt);
      } else {
        this.statusMessage.set(`A gerar vídeo (${cost} créditos)...`);
        // Gemini service returns a blob URL for video
        url = await this.geminiService.generateVideo(currentPrompt);
      }

      this.generatedUrl.set(url);
      
      const userId = this.currentUserId();
      if (userId) {
        // Guardar na BD
        // Nota: Blob URLs de vídeo expiram. Base64 de vídeo é muito pesado para TEXT column.
        // O ideal é usar Supabase Storage, mas aqui guardamos a URL temporária ou Base64 se possível.
        let storageUrl = url;
        if (this.mediaType() === 'video') {
           // Em produção, farias upload do blob para Storage e guardarias a URL pública.
           storageUrl = "Vídeo gerado (Storage não configurado)"; 
        }

        const savedItem = await this.supabaseService.addToHistory(userId, this.mediaType(), currentPrompt, storageUrl, cost);
        this.history.update(prev => [savedItem, ...prev]);

        // Deduzir créditos
        const newCredits = this.credits() - cost;
        await this.supabaseService.updateCredits(userId, newCredits);
        this.credits.set(newCredits);
      }

    } catch (err: any) {
      this.error.set(err.message || 'Erro inesperado.');
    } finally {
      this.isLoading.set(false);
      this.statusMessage.set('');
    }
  }

  setMediaType(type: MediaType) {
    this.mediaType.set(type);
    this.error.set(null);
    this.generatedUrl.set(null);
    this.isEditing.set(false);
  }

  selectHistoryItem(item: HistoryItem) {
    this.prompt.set(item.prompt);
    this.mediaType.set(item.type);
    this.generatedUrl.set(item.url);
    this.error.set(null);
    this.activeTab.set('studio');
    this.isEditing.set(false);
    if (window.innerWidth < 768) {
      this.isSidebarOpen.set(false);
    }
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  get isFormValid(): boolean {
    return this.prompt().trim().length > 0;
  }
}
